### ISSUE TITLE
I have no idea how to make this one work

### ISSUE THREAD

**Issue by Sadso23** [picrin/practicingFoundations#2]
' This subroutine takes an array of elements. Put element of index 1 in place of element of index 0, element of index 2 in place of element of index 1 and so on. Put element of index 0 in place of element of the last index. For example:
        ' anArray is initially (4, 8, 9, 3)
        '(3, 4, 8, 9)
        '(9, 3, 4, 8)
        '(8, 9, 3, 4)
        ' rotate(anArray)
        ' anArray is now (8, 9, 3, 4)                           Last element to the front push everything forwards by one, Repeat until 8 is at the front
        Sub rotateLeft(ByRef Rotate As ArrayList)

            Dim Temp1 As Integer
            Dim Temp2 As Integer

            If Rotate(0) = 8 Then

            Else
                Temp1 = Rotate(0)
                Rotate(0) = Rotate(3)
                Temp2 = Rotate(2)
                Rotate(2) = Rotate(1)
                Rotate(3) = Temp2
            End If
    End sub

    Test code

    Sub RotateLeftTest()
            Dim Rotate As ArrayList = New ArrayList(New Integer() {4, 8, 9, 3})
            rotateLeft(Rotate)
            If Rotate(0) <> 8 Then
                intAssertionError("RotateLeft", 4, Rotate(1))
            End If
        
        End Sub

**Comment by picrin** [comment]
Hi, sorry I'm so late, I've set up now e-mail notifications to those issues, which means I won't miss them that easily.

I think you need to rethink your approach, rotating right multiple times is more complicated logic then rotating right only once.

The algorithm you need to discover to do this uses a loop and a "busy" temporary variable, which is you need to assign to in every pass of the loop.
